# Example configuration using Envoy v2 bootstrap, custom envoy configuration with SNI and
# sample 'zero vpn' port forwarding. This needs to be manually updated for new domains and services,
# work in progress to automate it by having Pilot generate LDS v2 with SNI and capture the zvpn ports from
# annotations.
#
# Setting up SNI in LDSv2:
# https://www.envoyproxy.io/docs/envoy/latest/faq/sni.html#faq-how-to-setup-sni
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: istio-system
data:
  envoy-custom.yaml: |
    # You can include a custom bootstrap envoy yaml, updating the path in the 'args'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingress
  namespace: istio-system
  annotations:
    sidecar.istio.io/inject: "false"
    keel.sh/pollSchedule: "@every 10m"
  labels:
    # Will auto-update on gcr.io pushes
    keel.sh/policy: force
    keel.sh/trigger: poll

spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        keel.sh/pollSchedule: "@every 30m"
      labels:
        istio: ingress
        # Will auto-update on gcr.io pushes
        keel.sh/policy: force
        keel.sh/trigger: poll
    spec:
      serviceAccountName: istio-ingress-service-account
      containers:
      - name: istio-ingress
        # Manually start envoy, without using pilot-agent, so we can override the config.
        command: ["/usr/local/bin/envoy"]
        image: gcr.io/istio-testing/proxy_debug:weekly-staging
        # Configuration matching pilot-agent.
        args: ["-c", "/etc/envoy/envoy.yaml", "-l", "info", "--service-cluster", "istio-ingress", "--service-node" , "ingress~~istio-ingress.istio-system~istio-system.svc.cluster.local"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        # Static config
        - containerPort: 8080
        - containerPort: 8443
        # Ports for control plane, zero vpn
        - containerPort: 15003
        - containerPort: 15006
        - containerPort: 8060
        # Additional ports for 'zero vpn' using separate ports. Must have a corresponding port in
        # the service.
        - containerPort: 8081
        - containerPort: 5201
        - containerPort: 5202
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: VER
          value: "1"
        - name: RELOAD
          value: "11"

        volumeMounts:
        - name: istio-certs
          mountPath: /etc/certs
          readOnly: true
        - name: envoyconfig
          mountPath: /etc/envoy
        # Original multi-SAN default cert.
        - name: httpbin-tls
          mountPath: /etc/istio/ingress-certs
          readOnly: true
        # SNI certs
        - name: httpbin-tls
          mountPath: /etc/istio/httpbin-certs
          readOnly: true
        - name: httpbin-raw-tls
          mountPath: /etc/istio/httpbin-raw-certs
          readOnly: true
        resources:
          requests:
            cpu: 1500m
            memory: "1G"
          limits:
            cpu: 2000m
            memory: "2G"
      volumes:
      - name: istio-certs
        secret:
          secretName: istio.default
          optional: true
      # Manually mount until node-agent can automate it
      - name: httpbin-raw-tls
        secret:
            secretName: httpbin-raw-tls
            optional: true
      - name: httpbin-tls
        secret:
            secretName: httpbin-tls
            optional: true
      - name: ingress-certs
        secret:
          secretName: istio-ingress-certs
          optional: true
      - name: envoyconfig
        configMap:
            name: envoy-config

---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    istio: ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  # Additional ports for control plane, mesh using zero vpn
  - port: 15003
    name: http-pilot
  - port: 15006
    name: grpc-mixer
  - port: 8060
    name: grpc-ca
  # Additional ports for services exposed using zero vpn. For each service add a port here.
  - port: 5201
    name: iperf3
  - port: 5202
    name: iperf3-raw
  - port: 8081
    name: http-test
  - port: 8080
    name: http-manual
  - port: 8443
    name: https-manual
  selector:
    istio: ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-service-account
  namespace: istio-system
---
